FROM node:20-alpine AS base

WORKDIR /app

COPY apps/web/package*.json ./
RUN npm install

COPY apps/web/ .
RUN npm run build

FROM node:20-alpine AS production
WORKDIR /app

COPY --from=base /app/.next/standalone ./
COPY --from=base /app/.next/static ./.next/static


EXPOSE 3000

ENV PORT=3000
CMD ["node", "server.js"]
